name: telephony-service
version: 0.1+17.04.20161213.1-0ubuntu1
summary: Telephony service components for Ubuntu - backend
description: 
  Telephony service components for Ubuntu.
  .
  This package contains the backend components providing the telephony 
  features such as calling and texting.
confinement: devmode
grade: devel

apps:
  indicator:
    command: desktop-launch $SNAP/usr/bin/telephony-service-indicator
    plugs: [platform]

  handler:
    command: desktop-launch $SNAP/usr/bin/telephony-service-handler
    plugs: [platform]

  approver:
    command: desktop-launch $SNAP/usr/bin/telephony-service-approver
    plugs: [platform]

plugs:
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform

#slots:
#  telephony:
#    interface: telephony

parts:
  telephony-service:
    plugin: cmake
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCMAKE_CROSSCOMPILING=On]
    source: .
    build-packages:
      - cmake
      - dh-translations
      - dconf-cli
      - gnome-keyring
      - gsettings-ubuntu-schemas
      - libhistoryservice-dev
      - libicu-dev
      - libmessaging-menu-dev
      - libnotify-dev
      - libphonenumber-dev
      - libtelepathy-qt5-dev
      - libubuntu-application-api-dev
      - libprotobuf-dev
      - pkg-config
      - qt5-default
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtdeclarative5-dev-tools
      - qtfeedback5-dev
      - qtdeclarative5-ubuntu-ui-toolkit-plugin
      - qtmultimedia5-dev
      - qtpim5-dev
      - libusermetricsinput1-dev
      - telepathy-mission-control-5
      - upstart
    stage-packages:
      - accountsservice-ubuntu-touch-schemas
      - gsettings-ubuntu-schemas
      - history-service
      - libnotify4
      - telepathy-mission-control-5
      - ubuntu-sounds
      - tone-generator
      - libusermetricsinput1
      - dconf-cli
    after: [desktop-ubuntu-app-platform]

  environment:
    source: snap
    plugin: dump

